version: "3"

services:
  db:
    container_name: camagru-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - camagru_network
    restart: always

  phpmyadmin:
    container_name: camagru-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
    ports:
      - 81:80
    networks:
      - camagru_network
    restart: always

  app:
    container_name: camagru-app
    image: camagru-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SMTP_USERNAME=${SMTP_USERNAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - db
    environment:
      MYSQL_SERVERNAME: ${MYSQL_SERVERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - uploads:/src/uploads
      - ./src:/var/www/html
    networks:
      - camagru_network
    restart: always

  nginx:
    container_name: camagru-nginx
    image: nginx:latest
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - camagru_network
    restart: always

networks:
  camagru_network:
    name: camagru_network

volumes:
  database:
  uploads:
