version: "3"

services:
  db:
    container_name: camagru-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: camagru-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
    ports:
      - 8081:80
    restart: always

  app:
    container_name: camagru-app
    image: php:7.4-apache
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    restart: always

volumes:
  db:
